In [3]:
import numpy as np

#### creating numpy array

In [4]:
data = [1,2,3]

In [5]:
data

[1, 2, 3]

In [6]:
type(data)

list

In [7]:
arr = np.array(data)

In [8]:
arr


array([1, 2, 3])

In [9]:
type(arr)

numpy.ndarray

### built in methods in numpy

In [10]:
d= np.arange(10)
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
d = np.arange(5,10)
d

array([5, 6, 7, 8, 9])

In [12]:
d = np.arange(5,10,2)
d

array([5, 7, 9])

In [13]:
d = np.arange(5,10,0.5)
d

array([5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [14]:
d = np.arange(10,5,-0.4)
d

array([10. ,  9.6,  9.2,  8.8,  8.4,  8. ,  7.6,  7.2,  6.8,  6.4,  6. ,
        5.6,  5.2])

### ones and zeros

In [15]:
np.zeros(2)

array([0., 0.])

In [16]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

### linspaces

In [19]:
np.linspace(2,3,10) #10 numbers between 2 and 3

array([2.        , 2.11111111, 2.22222222, 2.33333333, 2.44444444,
       2.55555556, 2.66666667, 2.77777778, 2.88888889, 3.        ])

In [20]:
np.linspace(2,3,10,dtype=str)

array(['2.0', '2.111111111111111', '2.2222222222222223',
       '2.3333333333333335', '2.4444444444444446', '2.5555555555555554',
       '2.6666666666666665', '2.7777777777777777', '2.888888888888889',
       '3.0'], dtype='<U32')

In [21]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [22]:
np.eye(3,4,1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
np.eye(3,4,2)+9

array([[ 9.,  9., 10.,  9.],
       [ 9.,  9.,  9., 10.],
       [ 9.,  9.,  9.,  9.]])

### random

In [24]:
np.random.rand(2,3)

array([[0.29070482, 0.63133656, 0.1437049 ],
       [0.59783229, 0.66300865, 0.65783202]])

In [25]:
np.random.randn(2,3)+9

array([[ 9.37593813,  7.33204812,  7.62900528],
       [ 9.56384914, 10.02411738,  7.28585483]])

In [26]:
np.random.randint(2,10,20) #20 random values

array([5, 3, 6, 9, 9, 4, 9, 6, 9, 5, 2, 2, 9, 5, 9, 2, 3, 4, 4, 6])

In [27]:
np.random.randint(2,10,(2,4))

array([[9, 5, 7, 8],
       [4, 3, 7, 4]])

### Array attributes and methods

In [28]:
arr = np.linspace(10,20,6)
arr


array([10., 12., 14., 16., 18., 20.])

In [29]:
arr =arr.reshape(2,3)
arr

array([[10., 12., 14.],
       [16., 18., 20.]])

In [30]:
arr.shape

(2, 3)

In [31]:
arr.dtype

dtype('float64')

### indexing and selection

In [32]:
ar = np.arange(-10,9)
ar[-3]

6

In [33]:
ar[:5]

array([-10,  -9,  -8,  -7,  -6])

In [34]:
ar[::-1] #reverse

array([  8,   7,   6,   5,   4,   3,   2,   1,   0,  -1,  -2,  -3,  -4,
        -5,  -6,  -7,  -8,  -9, -10])

In [35]:
ar


array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8])

In [36]:
ar[::2]

array([-10,  -8,  -6,  -4,  -2,   0,   2,   4,   6,   8])

In [37]:
arr = np.arange(2,10,1)
arr

array([2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
arr = arr.reshape(4,2)
arr

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [39]:
arr[0][1]

3

### broadcasting

In [40]:
ar[:5]=10
ar

array([10, 10, 10, 10, 10, -5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,
        7,  8])

In [41]:
copy_ar = ar.copy()
copy_ar

array([10, 10, 10, 10, 10, -5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,
        7,  8])

In [43]:
arr = np.array(([1,2,3],[4,5,6]))
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
arr[0,2]


3

In [46]:
arr[-1]

array([4, 5, 6])