In [47]:
import numpy as np

#### creating numpy array

In [48]:
data = [1,2,3]

In [49]:
data

[1, 2, 3]

In [50]:
type(data)

list

In [51]:
arr = np.array(data)

In [52]:
arr


array([1, 2, 3])

In [53]:
type(arr)

numpy.ndarray

### built in methods in numpy

In [54]:
d= np.arange(10)
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
d = np.arange(5,10)
d

array([5, 6, 7, 8, 9])

In [56]:
d = np.arange(5,10,2)
d

array([5, 7, 9])

In [57]:
d = np.arange(5,10,0.5)
d

array([5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [58]:
d = np.arange(10,5,-0.4)
d

array([10. ,  9.6,  9.2,  8.8,  8.4,  8. ,  7.6,  7.2,  6.8,  6.4,  6. ,
        5.6,  5.2])

### ones and zeros

In [59]:
np.zeros(2)

array([0., 0.])

In [60]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [61]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [62]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

### linspaces

In [63]:
np.linspace(2,3,10) #10 numbers between 2 and 3

array([2.        , 2.11111111, 2.22222222, 2.33333333, 2.44444444,
       2.55555556, 2.66666667, 2.77777778, 2.88888889, 3.        ])

In [64]:
np.linspace(2,3,10,dtype=str)

array(['2.0', '2.111111111111111', '2.2222222222222223',
       '2.3333333333333335', '2.4444444444444446', '2.5555555555555554',
       '2.6666666666666665', '2.7777777777777777', '2.888888888888889',
       '3.0'], dtype='<U32')

In [65]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [66]:
np.eye(3,4,1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [67]:
np.eye(3,4,2)+9

array([[ 9.,  9., 10.,  9.],
       [ 9.,  9.,  9., 10.],
       [ 9.,  9.,  9.,  9.]])

### random

In [68]:
np.random.rand(2,3)

array([[0.82343325, 0.30744212, 0.97789457],
       [0.19444399, 0.21232542, 0.3701445 ]])

In [69]:
np.random.randn(2,3)+9

array([[ 8.07974831,  7.00795835, 11.21776137],
       [ 9.4443489 ,  6.68620616,  8.50607181]])

In [70]:
np.random.randint(2,10,20) #20 random values

array([3, 9, 9, 3, 9, 5, 3, 6, 9, 9, 9, 2, 7, 7, 4, 4, 4, 6, 9, 8])

In [71]:
np.random.randint(2,10,(2,4))

array([[7, 6, 8, 3],
       [8, 8, 7, 9]])

### Array attributes and methods

In [72]:
arr = np.linspace(10,20,6)
arr


array([10., 12., 14., 16., 18., 20.])

In [73]:
arr =arr.reshape(2,3)
arr

array([[10., 12., 14.],
       [16., 18., 20.]])

In [74]:
arr.shape

(2, 3)

In [75]:
arr.dtype

dtype('float64')

### indexing and selection

In [76]:
ar = np.arange(-10,9)
ar[-3]

6

In [77]:
ar[:5]

array([-10,  -9,  -8,  -7,  -6])

In [78]:
ar[::-1] #reverse

array([  8,   7,   6,   5,   4,   3,   2,   1,   0,  -1,  -2,  -3,  -4,
        -5,  -6,  -7,  -8,  -9, -10])

In [79]:
ar


array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8])

In [80]:
ar[::2]

array([-10,  -8,  -6,  -4,  -2,   0,   2,   4,   6,   8])

In [81]:
arr = np.arange(2,10,1)
arr

array([2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
arr = arr.reshape(4,2)
arr

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [83]:
arr[0][1]

3

### broadcasting

In [84]:
ar[:5]=10
ar

array([10, 10, 10, 10, 10, -5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,
        7,  8])

In [85]:
copy_ar = ar.copy()
copy_ar

array([10, 10, 10, 10, 10, -5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,
        7,  8])

In [86]:
arr = np.array(([1,2,3],[4,5,6]))
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
arr[0,2]


3

In [88]:
arr[-1]

array([4, 5, 6])

In [89]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [90]:
arr[:,:-1] #all rows and columns till -1th

array([[1, 2],
       [4, 5]])

In [91]:
arr[1:3,:]

array([[4, 5, 6]])

In [92]:
arr[:,0]

array([1, 4])

### fancy indexing

In [93]:
arr = np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [94]:
arr.shape[1] # number of columns

4

In [95]:
for i in range(arr.shape[0]):
    arr[i] = i
    print(arr[i])

[0. 0. 0. 0.]
[1. 1. 1. 1.]
[2. 2. 2. 2.]


### selection

In [96]:
arr = np.arange(0,11)
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [97]:
arr>4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

## Numpy operation

In [98]:
arr1 = np.linspace(2,100,10)

In [99]:
arr2 = np.linspace(450,900,10)

In [100]:
arr1

array([  2.        ,  12.88888889,  23.77777778,  34.66666667,
        45.55555556,  56.44444444,  67.33333333,  78.22222222,
        89.11111111, 100.        ])

In [101]:
arr2

array([450., 500., 550., 600., 650., 700., 750., 800., 850., 900.])

In [102]:
arr1+arr2

array([ 452.        ,  512.88888889,  573.77777778,  634.66666667,
        695.55555556,  756.44444444,  817.33333333,  878.22222222,
        939.11111111, 1000.        ])

In [103]:
arr1-arr2

array([-448.        , -487.11111111, -526.22222222, -565.33333333,
       -604.44444444, -643.55555556, -682.66666667, -721.77777778,
       -760.88888889, -800.        ])

In [104]:
arr1/arr2

array([0.00444444, 0.02577778, 0.04323232, 0.05777778, 0.07008547,
       0.08063492, 0.08977778, 0.09777778, 0.1048366 , 0.11111111])

In [105]:
arr1**2 #power

array([4.00000000e+00, 1.66123457e+02, 5.65382716e+02, 1.20177778e+03,
       2.07530864e+03, 3.18597531e+03, 4.53377778e+03, 6.11871605e+03,
       7.94079012e+03, 1.00000000e+04])

### universal array function

In [106]:
arr1 = np.arange(0,10)

In [107]:
np.sqrt(arr1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [108]:
np.exp(arr1)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [109]:
np.max(arr1)

9

In [110]:
np.log(arr1)

C:\Users\Vaibhav Thalanki\AppData\Local\Temp\ipykernel_1036\2108464003.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr1)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [111]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [112]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [113]:
arr1 = np.array([[10,11,12]])
arr1

array([[10, 11, 12]])

In [114]:
np.append(arr,arr1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [115]:
arr.shape

(3, 3)

In [116]:
arr1.shape

(1, 3)

In [117]:
np.append(arr,arr1,0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [118]:
arr1=arr1.transpose()

In [119]:
np.append(arr,arr1,1)

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 12]])

In [120]:
np.concatenate((arr,arr1),1)

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 12]])

In [121]:
arr1=arr1.transpose()

In [122]:
np.concatenate((arr,arr1),0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### Stack

In [123]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [124]:
arr1

array([[10, 11, 12]])

In [125]:
np.vstack((arr1,arr)) #horizontal stack

array([[10, 11, 12],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [126]:
arr1=arr1.transpose()

In [127]:
np.hstack((arr,arr1)) #horizontal stack

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 12]])

In [129]:
ar1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
ar1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [148]:
ar2  = np.array([[2,2,2,3]])
ar2

array([[2, 2, 2, 3]])

In [149]:
np.append(ar1,ar2,0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 2,  2,  2,  3]])