In [2]:
import pandas as pd
import numpy as np


In [3]:
#churn modelling - if customer is staying or leaving for competitor
df = pd.read_csv('D:\codes_programming\py files\Datasets\Churn_Modelling.csv')
df

RowNumber  CustomerId    Surname  CreditScore Geography  Gender   Age  \
0             1    15634602   Hargrave          619    France  Female  42.0   
1             2    15647311       Hill          225     Spain  Female  41.0   
2             3    15619304       Onio          629    France  Female  42.0   
3             4    15701354       Boni          699    France  Female  39.0   
4             5    15737888   Mitchell          850       NaN  Female  43.0   
...         ...         ...        ...          ...       ...     ...   ...   
9995       9996    15606229   Obijiaku          771    France    Male  39.0   
9996       9997    15569892  Johnstone          516    France    Male  35.0   
9997       9998    15584532        Liu          709    France  Female  36.0   
9998       9999    15682355  Sabbatini          772   Germany    Male  42.0   
9999      10000    15628319     Walker          792    France  Female  28.0   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [4]:
df.isnull().any() #null values iN geography, gender,age,balance

RowNumber          False
CustomerId         False
Surname            False
CreditScore        False
Geography           True
Gender              True
Age                 True
Tenure             False
Balance             True
NumOfProducts      False
HasCrCard          False
IsActiveMember     False
EstimatedSalary    False
Exited             False
dtype: bool

In [5]:
df.shape

(10000, 14)

In [6]:
type(df)

pandas.core.frame.DataFrame

In [7]:
df.info() 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        9999 non-null   object 
 5   Gender           9999 non-null   object 
 6   Age              9999 non-null   float64
 7   Tenure           10000 non-null  int64  
 8   Balance          9999 non-null   float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(3), int64(8), object(3)
memory usage: 1.1+ MB


In [8]:
df.describe()

RowNumber    CustomerId  CreditScore          Age        Tenure  \
count  10000.00000  1.000000e+04  10000.00000  9999.000000  10000.000000   
mean    5000.50000  1.569094e+07    650.48290    38.924892      5.012800   
std     2886.89568  7.193619e+04     96.72014    10.486670      2.892174   
min        1.00000  1.556570e+07    225.00000    18.000000      0.000000   
25%     2500.75000  1.562853e+07    584.00000    32.000000      3.000000   
50%     5000.50000  1.569074e+07    652.00000    37.000000      5.000000   
75%     7500.25000  1.575323e+07    717.25000    44.000000      7.000000   
max    10000.00000  1.581569e+07    850.00000    92.000000     10.000000   

             Balance  NumOfProducts    HasCrCard  IsActiveMember  \
count    9999.000000   10000.000000  10000.00000    10000.000000   
mean    76483.536070       1.530200      0.70550        0.515100   
std     62400.186375       0.581654      0.45584        0.499797   
min         0.000000       1.000000      0.00000        0.000000   
25%         0.000000       1.000000      0.00000        0.000000   
50%     97188.620000       1.000000      1.00000        1.000000   
75%    127646.040000       2.000000      1.00000        1.000000   
max    250898.090000       4.000000      1.00000        1.000000   

       EstimatedSalary        Exited  
count     10000.000000  10000.000000  
mean     100090.239881      0.203700  
std       57510.492818      0.402769  
min          11.580000      0.000000  
25%       51002.110000      0.000000  
50%      100193.915000      0.000000  
75%      149388.247500      0.000000  
max      199992.480000      1.000000

In [9]:
df.isnull()

RowNumber  CustomerId  Surname  CreditScore  Geography  Gender    Age  \
0         False       False    False        False      False   False  False   
1         False       False    False        False      False   False  False   
2         False       False    False        False      False   False  False   
3         False       False    False        False      False   False  False   
4         False       False    False        False       True   False  False   
...         ...         ...      ...          ...        ...     ...    ...   
9995      False       False    False        False      False   False  False   
9996      False       False    False        False      False   False  False   
9997      False       False    False        False      False   False  False   
9998      False       False    False        False      False   False  False   
9999      False       False    False        False      False   False  False   

      Tenure  Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0      False    False          False      False           False   
1      False    False          False      False           False   
2      False    False          False      False           False   
3      False    False          False      False           False   
4      False    False          False      False           False   
...      ...      ...            ...        ...             ...   
9995   False    False          False      False           False   
9996   False    False          False      False           False   
9997   False    False          False      False           False   
9998   False    False          False      False           False   
9999   False    False          False      False           False   

      EstimatedSalary  Exited  
0               False   False  
1               False   False  
2               False   False  
3               False   False  
4               False   False  
...               ...     ...  
9995            False   False  
9996            False   False  
9997            False   False  
9998            False   False  
9999            False   False  

[10000 rows x 14 columns]

In [11]:
#replace null with either mode, median or mean
#use mode when we have categories, here geography and gender
#for small range numerical data use mean, here age
#for large range numerical data use median, here balance


In [12]:
df['Geography'].fillna(df['Geography'].mode()[0],inplace=True) #inplace=true makes changes permanent

In [13]:
df['Gender'].fillna(df['Gender'].mode()[0],inplace=True) #inplace=true makes changes permanent

In [14]:
df['Age'].fillna(df['Age'].mean(),inplace=True) #inplace=true makes changes permanent

In [15]:
df['Balance'].fillna(df['Balance'].median(),inplace=True) #inplace=true makes changes permanent

In [16]:
df

RowNumber  CustomerId    Surname  CreditScore Geography  Gender   Age  \
0             1    15634602   Hargrave          619    France  Female  42.0   
1             2    15647311       Hill          225     Spain  Female  41.0   
2             3    15619304       Onio          629    France  Female  42.0   
3             4    15701354       Boni          699    France  Female  39.0   
4             5    15737888   Mitchell          850    France  Female  43.0   
...         ...         ...        ...          ...       ...     ...   ...   
9995       9996    15606229   Obijiaku          771    France    Male  39.0   
9996       9997    15569892  Johnstone          516    France    Male  35.0   
9997       9998    15584532        Liu          709    France  Female  36.0   
9998       9999    15682355  Sabbatini          772   Germany    Male  42.0   
9999      10000    15628319     Walker          792    France  Female  28.0   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [19]:
df.isnull().any()

RowNumber          False
CustomerId         False
Surname            False
CreditScore        False
Geography          False
Gender             False
Age                False
Tenure             False
Balance            False
NumOfProducts      False
HasCrCard          False
IsActiveMember     False
EstimatedSalary    False
Exited             False
dtype: bool

In [20]:
df['Geography'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [21]:
df['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [23]:
#convert textual data to numerical using label encoding
#label encoding works in alphabetical order so France will be 0,germany will be 1, spain will be 2
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [24]:
df['Geography'] = le.fit_transform(df['Geography'])
df['Gender'] = le.fit_transform(df['Gender'])

In [25]:
df

RowNumber  CustomerId    Surname  CreditScore  Geography  Gender   Age  \
0             1    15634602   Hargrave          619          0       0  42.0   
1             2    15647311       Hill          225          2       0  41.0   
2             3    15619304       Onio          629          0       0  42.0   
3             4    15701354       Boni          699          0       0  39.0   
4             5    15737888   Mitchell          850          0       0  43.0   
...         ...         ...        ...          ...        ...     ...   ...   
9995       9996    15606229   Obijiaku          771          0       1  39.0   
9996       9997    15569892  Johnstone          516          0       1  35.0   
9997       9998    15584532        Liu          709          0       0  36.0   
9998       9999    15682355  Sabbatini          772          1       1  42.0   
9999      10000    15628319     Walker          792          0       0  28.0   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [26]:
#in gender is easy, 0-false-female 1-true-male
#but in geography, we have 0,1,2 to represent different categories, not numerical dats
# so convert into categorical values using one hot encoder
#it'll be converted to 3 columnsacting like a truth table but since simultaneous isnt possible it'll be 100 010 001


In [63]:
#divide data into dependant and independant
#use values to convert to numpy arrays
x=df.iloc[:,3:13].values
y=df.iloc[:,13:].values

In [64]:
x

array([[6.1900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [2.2500000e+02, 2.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [6.2900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [7.0900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [7.7200000e+02, 1.0000000e+00, 1.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [7.9200000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [65]:
type(x)

numpy.ndarray

In [66]:
#onehot encoding on geography
from sklearn.preprocessing import OneHotEncoder
one = OneHotEncoder()
z= one.fit_transform(x[:,1:2]).toarray()

In [67]:
z

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [68]:
x.shape

(10000, 10)

In [69]:

x = np.delete(x,1,axis=1) #axis 1 means column
x.shape

(10000, 9)

In [70]:
#concatenate z to x
x = np.concatenate((z,x),axis=1)
x

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [71]:
x.shape

(10000, 12)

In [73]:
#splitting train-test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2,random_state=0)
#0.2 means 20% data will be test
print(x_train.shape)
print(x_test.shape)

(8000, 12)
(2000, 12)


In [75]:
#feature scaling
#standard scaling = (x-mean)/std. dev
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [76]:
x_train

array([[-1.0148604 , -0.5698444 ,  1.74367544, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-1.0148604 ,  1.75486502, -0.57350122, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [ 0.98535719, -0.5698444 , -0.57350122, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.98535719, -0.5698444 , -0.57350122, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-1.0148604 , -0.5698444 ,  1.74367544, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-1.0148604 ,  1.75486502, -0.57350122, ...,  0.64259497,
        -1.03227043,  0.32472465]])